#pragma once
#include <iostream>
#include <string>
#include <memory>
#include <list>
#include <sstream>
#include <fstream>
#include <vector>
#include <map>
#include <functional>
#include <ctime>
#include <cstring>
#include <thread>
#include <cassert>

using std::string;
using std::list;
using std::vector;
using std::pair;
using std::to_string;
using std::shared_ptr;
using std::ostream;
using std::ofstream;
using std::stringstream;
using std::cout;
using std::endl;
using std::function;
using std::make_pair;